import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Swal from 'sweetalert2';
import api, { getErrorMessage } from '../api/client';

const Signup = () => {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('Resident'); const [showPassword, setShowPassword] = useState(false); const [isSubmitting, setIsSubmitting] = useState(false); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); if (password.length < 8) return Swal.fire({ icon: 'error', title: 'Password too short', text: 'Use at least 8 characters.' }); try { setIsSubmitting(true); await api.post('/api/auth/register', { name, email, password, role }); await Swal.fire({ icon: 'success', title: 'Account created', text: 'You can now sign in.' }); navigate('/login'); } catch (error) { Swal.fire({ icon: 'error', title: 'Could not create account', text: getErrorMessage(error) }); } finally { setIsSubmitting(false); } };
  return <main className="auth-page"><section className="auth-intro"><div className="auth-intro-content"><div className="auth-logo"><i className="fa-solid fa-building-shield" /></div><span className="auth-eyebrow">SOCIETY HUB</span><h1>Join a smarter, more connected community.</h1><p>Create your profile to securely access the services relevant to your role.</p><div className="auth-feature"><i className="fa-solid fa-circle-check" /> Clear role-specific workspace</div><div className="auth-feature"><i className="fa-solid fa-people-group" /> Built for daily society operations</div></div></section><section className="auth-panel"><div className="auth-card"><div className="auth-mobile-brand"><i className="fa-solid fa-building-shield" /> Society Hub</div><div className="auth-heading"><span className="auth-kicker">GET STARTED</span><h2>Create your account</h2><p>Fill in your details to join the society portal.</p></div><form onSubmit={submit}><div className="auth-field"><label htmlFor="name">Full name</label><div className="auth-input"><i className="fa-regular fa-user" /><input id="name" required autoComplete="name" placeholder="Your full name" value={name} onChange={(e) => setName(e.target.value)} /></div></div><div className="auth-field"><label htmlFor="email">Email address</label><div className="auth-input"><i className="fa-regular fa-envelope" /><input id="email" required type="email" autoComplete="email" placeholder="name@example.com" value={email} onChange={(e) => setEmail(e.target.value)} /></div></div><div className="auth-field"><label htmlFor="role">Account role</label><div className="auth-input"><i className="fa-solid fa-user-tag" /><select id="role" value={role} onChange={(e) => setRole(e.target.value)}><option value="Resident">Resident</option><option value="Admin">Administrator</option><option value="Guard">Security guard</option></select></div></div><div className="auth-field"><label htmlFor="password">Password</label><div className="auth-input"><i className="fa-solid fa-lock" /><input id="password" required minLength="8" type={showPassword ? 'text' : 'password'} autoComplete="new-password" placeholder="At least 8 characters" value={password} onChange={(e) => setPassword(e.target.value)} /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Toggle password visibility"><i className={`fa-solid ${showPassword ? 'fa-eye-slash' : 'fa-eye'}`} /></button></div></div><button disabled={isSubmitting} className="auth-submit">{isSubmitting ? 'Creating account…' : 'Create account'} <i className="fa-solid fa-arrow-right" /></button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></div></section></main>;
};
export default Signup;
